[package]
name = "sharing-endpoint"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies]
common-base = { path = "../../common/base" }
common-config = { path = "../../query/config" }
common-exception = { path = "../../common/exception" }
common-storage = { path = "../../common/storage" }
once_cell = "1.15.0"
uuid = { version = "1.1.2", features = ["serde", "v4"] }

time = { version = "0.3", features = ["serde"] }

anyhow = { workspace = true }
base64 = "0.13.0"
clap = { workspace = true }
opendal = "0.22.2"
poem = { version = "1", features = ["rustls", "multipart", "compression"] }
serde = { workspace = true }
serde_json = { workspace = true }
serfig = "0.0.3"
thiserror = { version = "1" }
