[package]
name = "sharing-endpoint"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies]
async-backtrace = { workspace = true }
chrono = { workspace = true }
common-base = { path = "../../common/base" }
common-config = { path = "../../query/config" }
common-exception = { path = "../../common/exception" }
common-meta-app = { path = "../../meta/app" }
common-storage = { path = "../../common/storage" }
common-storages-share = { path = "../storages/share" }
uuid = { version = "1.1.2", features = ["serde", "v4"] }

time = { version = "0.3", features = ["serde"] }

base64 = "0.21.0"
clap = { workspace = true }
enumflags2 = { version = "0.7.5", features = ["serde"] }
opendal = { workspace = true }
poem = { version = "1", features = ["rustls", "multipart", "compression"] }
serde = { workspace = true }
serde_json = { workspace = true }
serfig = "0.1.0"
