[package]
name = "common-settings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[features]
hive = []

[dependencies]
common-ast = { path = "../../query/ast" }
common-base = { path = "../../common/base" }
common-config = { path = "../config" }
common-exception = { path = "../../common/exception" }
common-meta-types = { path = "../../meta/types" }
common-users = { path = "../users" }

dashmap = "5.4"
futures = "0.3.24"
itertools = "0.10.5"
num_cpus = "1.13.1"
tracing = "0.1.36"
