[package]
name = "common-proto-conv"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
common-datavalues = { path = "../../query/datavalues" }
common-expression = { path = "../../query/expression" }
common-meta-app = { path = "../app" }
common-meta-types = { path = "../types" }
common-protos = { path = "../protos" }
common-storage = { path = "../../common/storage" }

chrono = { workspace = true }
num = "0.4.0"
thiserror = { workspace = true }

enumflags2 = { version = "0.7.5", features = ["serde"] }

[build-dependencies]

[dev-dependencies]
anyhow = { workspace = true }
maplit = "1.0.2"
pretty_assertions = "1.3.0"
