[package]
name = "common-storage"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[features]
storage-hdfs = ["opendal/services-hdfs"]

[dependencies]
common-arrow = { path = "../arrow" }
common-auth = { path = "../auth" }
common-base = { path = "../base" }
common-exception = { path = "../exception" }

anyhow = { workspace = true }
async-trait = "0.1"
backon = "0.2"
bytes = "1"
futures = "0.3"
globiter = "0.1"
once_cell = "1"
opendal = { version = "0.22", features = [
    "layers-tracing",
    "layers-metrics",
    "services-ipfs",
    "services-ftp",
    "services-moka",
    "services-redis",
    "trust-dns",
    "compress",
] }
parking_lot = "0.12.1"
percent-encoding = "2"
serde = { workspace = true }
