[package]
name = "common-storage"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[features]
storage-hdfs = ["common-meta-types/storage-hdfs"]

[dependencies]
common-arrow = { path = "../arrow" }
common-auth = { path = "../auth" }
common-base = { path = "../base" }
common-exception = { path = "../exception" }
common-expression = { path = "../../query/expression" }
common-meta-types = { path = "../../meta/types" }

anyhow = { workspace = true }
async-stream = "0.3.3"
async-trait = "0.1"
backon = "0.2"
bytes = "1"
futures = "0.3"
globiter = "0.1"
once_cell = "1"
opendal = { workspace = true, features = [
    "layers-tracing",
    "layers-metrics",
    "services-ipfs",
    # Disable ftp support until https://github.com/datafuselabs/opendal/pull/1102 has been released
    # "services-ftp",
    "services-moka",
    "services-redis",
    "trust-dns",
    "compress",
] }
parking_lot = "0.12.1"
percent-encoding = "2"
regex = "1.6.0"
serde = { workspace = true }

[dev-dependencies]
