[package]
name = "common-storage"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[features]
storage-hdfs = ["common-meta-app/storage-hdfs"]

[dependencies]
common-arrow = { path = "../arrow" }
common-auth = { path = "../auth" }
common-base = { path = "../base" }
common-exception = { path = "../exception" }
common-expression = { path = "../../query/expression" }
common-meta-app = { path = "../../meta/app" }

anyhow = { workspace = true }
async-trait = "0.1"
bytes = "1"
chrono = { workspace = true }
flagset = "0.4"
futures = "0.3"
opendal = { workspace = true }
regex = "1.6.0"
serde = { workspace = true }

[dev-dependencies]
