name: "Test sqllogic Standalone"
description: "Running sqllogic tests in standalone mode"
inputs:
  profile:
    description: "The profile for this test"
    required: true
    default: "debug"
  target:
    description: ""
    required: true
    default: "x86_64-unknown-linux-gnu"
  dirs:
    description: "logic test suites dirs"
    required: true
    default: ""
  handlers:
    description: "logic test handlers, mysql,http,clickhouse"
    required: true
    default: ""
  storage-format:
    description: "storage format for databend query to test"
    required: true
    default: all

runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: ./.github/actions/artifact_download
      with:
        profile: ${{ inputs.profile }}
        sha: ${{ github.sha }}
        target: ${{ inputs.target }}
    - name: Run sqllogic Tests with Standalone mode
      if: inputs.storage-format == 'all' || inputs.storage-format == 'parquet'
      shell: bash
      env:
        TEST_HANDLERS: ${{ inputs.handlers }}
      run: bash ./scripts/ci/ci-run-sqllogic-tests.sh ${{ inputs.dirs }}
    - name: Run native sqllogic Tests with Standalone mode
      if: inputs.storage-format == 'all' || inputs.storage-format == 'native'
      shell: bash
      env:
        TEST_HANDLERS: ${{ inputs.handlers }}
      run: bash ./scripts/ci/ci-run-sqllogic-tests-native.sh ${{ inputs.dirs }}
