name: "Test sqllogic Standalone"
description: "Running sqllogic tests in standalone mode"
inputs:
  profile:
    description: "The profile for this test"
    required: true
    default: "debug"
  target:
    description: ""
    required: true
    default: "x86_64-unknown-linux-gnu"
  dirs:
    description: "logic test suites dirs"
    required: true
    default: ""
  handlers:
    description: "logic test handlers, mysql,http,clickhouse"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: ./.github/actions/artifact_download
      with:
        profile: ${{ inputs.profile }}
        sha: ${{ github.sha }}
        target: ${{ inputs.target }}

    - name: Run sqllogic Tests with Standalone mode
      shell: bash
      env:
        TEST_HANDLERS: ${{ inputs.handlers }}
      run: |
        docker run --rm --tty --net=host \
          --user $(id -u):$(id -g) \
          --env BUILD_PROFILE \
          --env TEST_HANDLERS \
          --ulimit nofile=65535:65535 \
          --ulimit stack=16777216:16777216 \
          --volume "${PWD}:/workspace" \
          --workdir "/workspace" \
          datafuselabs/build-tool:sqllogic \
          bash ./scripts/ci/ci-run-sqllogic-tests.sh \
          ${{ inputs.dirs }}
