[package]
name = "vacuum-handler"
description = "vacuum handler"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies
common-base = { path = "../../../common/base" }
common-catalog = { path = "../../catalog" }
common-exception = { path = "../../../common/exception" }
common-storages-fuse = { path = "../../storages/fuse" }

async-backtrace = { workspace = true }
async-trait = "0.1.57"
chrono = { workspace = true }

[build-dependencies]

[package.metadata.cargo-machete]
ignored = ["match-template"]
