name: "Test Unite"
description: "Running unit tests"
inputs:
  codecov_token:
    description: "CodeCov Token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Build Tool
      uses: ./.github/actions/setup_build_tool
      with:
        bypass_env_vars: RUSTFLAGS,RUSTDOCFLAGS,RUST_TEST_THREADS,RUST_LOG,RUST_BACKTRACE

    - shell: bash
      run: cargo -Z sparse-registry test
      env:
        RUST_TEST_THREADS: "2"
        RUST_LOG: INFO
        RUST_BACKTRACE: full

    - name: Upload failure
      if: failure()
      uses: ./.github/actions/artifact_failure
      with:
        name: test-unit
