name: "Test Unite"
description: "Running unit tests"

runs:
  using: "composite"
  steps:
    - name: Setup Build Tool
      uses: ./.github/actions/setup_build_tool
      with:
        bypass_env_vars: RUSTFLAGS,RUSTDOCFLAGS,RUST_TEST_THREADS,RUST_LOG,RUST_BACKTRACE

    - shell: bash
      run: cargo test
      env:
        RUST_TEST_THREADS: "2"
        RUST_LOG: INFO
        RUST_BACKTRACE: full

    - name: Upload failure
      if: failure() || cancelled()
      uses: ./.github/actions/artifact_failure
      with:
        name: test-unit
