[package]
name = "common-storages-factory"
version = "0.1.0"
edition = "2021"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-catalog = { path = "../../catalog" }
common-config = { path = "../../config" }
common-exception = { path = "../../../common/exception" }
common-meta-app = { path = "../../../meta/app" }
common-storages-fuse = { path = "../fuse/fuse" }
common-storages-index = { path = "../index" }
common-storages-memory = { path = "../memory" }
common-storages-null = { path = "../null" }
common-storages-random = { path = "../random" }
common-storages-view = { path = "../view" }

parking_lot = "0.12.1"
