[package]
name = "common-config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[features]
default = []
storage-hdfs = ["common-storage/storage-hdfs"]
hive = ["common-hive-meta-store", "thrift", "storage-hdfs"]

[package.metadata.cargo-machete]
ignored = ["thrift", "common-hive-meta-store", "strum"]

[dependencies]
common-base = { path = "../../common/base" }
common-exception = { path = "../../common/exception" }
common-grpc = { path = "../../common/grpc" }
common-hive-meta-store = { path = "../storages/hive/hive-meta-store", optional = true }
common-meta-types = { path = "../../meta/types" }
common-storage = { path = "../../common/storage" }
common-tracing = { path = "../../common/tracing" }
common-users = { path = "../users" }

thrift = { git = "https://github.com/datafuse-extras/thrift", tag = "v0.17.0", optional = true }

clap = { workspace = true }
hex = "0.4.3"
once_cell = "1.15.0"
semver = "1.0.14"
serde = { workspace = true }
serfig = "0.0.3"
strum = "0.24.1"
strum_macros = "0.24.1"

[build-dependencies]
common-building = { path = "../../common/building" }
