name: "Upload failure Artifacts"
description: "Upload failure Artifacts"
inputs:
  name:
    description: ""
    required: true
runs:
  using: "composite"
  steps:
    - name: pack failure artifacts
      shell: bash
      run: |
        tar --warning=no-file-changed \
            --exclude='target' \
            --exclude='website' \
            --exclude='docs' \
            --exclude='docker' \
            --exclude='bins' \
            --exclude='.git' \
            --exclude='tests/suites/0_stateless/13_tpch/data' \
            --exclude='failure-*' \
            -zcf failure-${{ inputs.name }}.tar.gz .
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: failure-${{ inputs.name }}.tar.gz
