name: "Upload failure Artifacts"
description: "Upload failure Artifacts"
inputs:
  name:
    description: ""
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: |
          .
          !./target
          !./website
          !./docs
          !./docker
          !./bins
          !./.git
          !./tests/suites/0_stateless/13_tpch/data
