[package]
name = "common-jsonb"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[dependencies]
byteorder = "1.4.3"
fast-float = "0.2.0"
ordered-float = { workspace = true, features = ["serde"] }
serde_json = { workspace = true }
