[package]
name = "codegen"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[[bin]]
name = "codegen"
path = "src/bin/codegen.rs"

[dependencies]
common-expression = { path = "../expression" }

itertools = "0.10"
