[package]
name = "common-meta-client"
description = "common meta grpc"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false
test = false

[dependencies]
common-arrow = { path = "../../common/arrow" }
common-base = { path = "../../common/base" }
common-grpc = { path = "../../common/grpc" }
common-meta-api = { path = "../api" }
common-meta-kvapi = { path = "../kvapi" }
common-meta-types = { path = "../types" }
common-metrics = { path = "../../common/metrics" }
common-tracing = { path = "../../common/tracing" }

derive_more = { workspace = true }
futures = "0.3.24"
once_cell = "1.15.0"
parking_lot = "0.12.1"
prost = { workspace = true }
semver = "1.0.14"
serde = { workspace = true }
serde_json = { workspace = true }
tonic = { version = "0.8.1", features = ["transport", "codegen", "prost", "tls-roots", "tls"] }
tracing = "0.1.36"

[dev-dependencies]
common-exception = { path = "../../common/exception" }
common-meta-app = { path = "../app" }

rand = "0.8.5"

[build-dependencies]
common-building = { path = "../../common/building" }
