name: "Test fuse-table format in an old query is compatible with new query"
description: "Download old binaries and current binaries, write data with old query, read data with new query"
inputs:
  target:
    description: ""
    required: true
    default: "x86_64-unknown-linux-gnu"
runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: ./.github/actions/artifact_download
      with:
        sha: ${{ github.sha }}
        target: ${{ inputs.target }}
        path: ./bins/current
        artifacts: sqllogictests,meta,query

    - name: Test compatibility
      shell: bash
      run: |
          bash ./tests/fuse-compat/test-fuse-compat.sh 0.7.150 base
          bash ./tests/fuse-compat/test-fuse-compat.sh 0.7.151 base
          bash ./tests/fuse-compat/test-fuse-compat.sh 1.0.56 base
          bash ./tests/fuse-compat/test-fuse-compat.sh 1.0.56 01_meta_compression 01_flashback
          bash ./tests/fuse-compat/test-fuse-compat.sh 1.1.30 base

    - name: Upload failure
      if: failure() || cancelled()
      uses: ./.github/actions/artifact_failure
      with:
        name: fuse-compat
