[workspace.package]
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[workspace]
members = [
    # Binaries
    "src/binaries",
    "src/binaries/meta-upgrade-09",
    # Common
    "src/common/arrow",
    "src/common/auth",
    "src/common/base",
    "src/common/building",
    "src/common/cache",
    "src/common/compress",
    "src/common/exception",
    "src/common/grpc",
    "src/common/hashtable",
    "src/common/http",
    "src/common/io",
    "src/common/metrics",
    "src/common/tracing",
    "src/common/storage",
    "src/common/profile",
    # Query
    "src/query/ast",
    "src/query/codegen",
    "src/query/config",
    "src/query/catalog",
    "src/query/sharing",
    "src/query/sharing-endpoint",
    "src/query/datavalues",
    "src/query/expression",
    "src/query/formats",
    "src/query/functions",
    "src/query/management",
    "src/query/pipeline/core",
    "src/query/pipeline/sinks",
    "src/query/pipeline/sources",
    "src/query/pipeline/transforms",
    "src/query/settings",
    "src/query/sql",
    "src/query/storages/common/blocks",
    "src/query/storages/common/cache",
    "src/query/storages/common/cache-manager",
    "src/query/storages/common/index",
    "src/query/storages/common/pruner",
    "src/query/storages/common/table-meta",
    "src/query/storages/factory",
    "src/query/storages/fuse",
    "src/query/storages/hive/hive",
    "src/query/storages/hive/hive-meta-store",
    "src/query/storages/iceberg",
    "src/query/storages/information-schema",
    "src/query/storages/memory",
    "src/query/storages/null",
    "src/query/storages/random",
    "src/query/storages/share",
    "src/query/storages/stage",
    "src/query/storages/system",
    "src/query/storages/view",
    "src/query/storages/parquet",
    "src/query/storages/result_cache",
    "src/query/users",
    # databend-query
    "src/query/service",
    # Meta
    "src/meta/api",
    "src/meta/app",
    "src/meta/embedded",
    "src/meta/kvapi",
    "src/meta/raft-store",
    "src/meta/sled-store",
    "src/meta/stoerr",
    "src/meta/store",
    "src/meta/types",
    # meta proto
    "src/meta/proto-conv",
    "src/meta/protos",
    # databend-meta
    "src/meta/service",
    # sqllogictest
    "tests/sqllogictests",
]

[workspace.dependencies]
# databend maintains:
sled = { git = "https://github.com/datafuse-extras/sled", tag = "v0.34.7-datafuse.1", default-features = false }
opendal = { version = "0.30", features = [
    "layers-tracing",
    "layers-metrics",
    "services-ipfs",
    "services-moka",
    "services-redis",
    "trust-dns",
] }
ordered-float = { version = "3.4.0", default-features = false }
jsonb = { version = "0.1.1" }

# openraft = { version = "0.8.2", features = ["compat-07"] }
# For debugging
openraft = { git = "https://github.com/drmingdrmer/openraft", tag = "v0.8.3-alpha.2", features = ["compat-07"] }

# type helper
derive_more = "0.99.17"

# error
anyhow = { version = "1.0.65" }
anyerror = { version = "=0.1.7" }
thiserror = { version = "1" }

# CLI
clap = { version = "3.2.22", features = ["derive", "env"] }

# serialization
prost = { version = "0.11.0" }
# 1.0.153 adds a new feature which will allow `serde(alias = "…")` inside a flattened struct.
# This feature seems cool but will break our config parse.
# @xuanwo will address this issue upon his return from Mars.
serde = { version = "=1.0.152", features = ["derive", "rc"] }
serde_json = { version = "1.0.85", default-features = false, features = ["preserve_order"] }

# chrono
chrono = { version = "0.4.24", features = ["serde"] }
chrono-tz = "0.6.3"

# memory
bumpalo = "3.12.0"
tikv-jemalloc-ctl = { version = "0.5.0", features = ["use_std"] }

# http
reqwest = { version = "0.11", default-features = false, features = [
    "json",
    "rustls-tls",
    "rustls-tls-native-roots",
    "trust-dns",
] }

# runtime
tokio = { version = "1.24.2", features = ["full"] }

[profile.release]
debug = 1
lto = "thin"
overflow-checks = false
codegen-units = 1       # Reduce number of codegen units to increase optimizations.

[profile.release.package]
arrow2 = { codegen-units = 4 }
common-functions = { codegen-units = 16 }
databend-query = { codegen-units = 4 }
databend-binaries = { codegen-units = 4 }

[profile.bench]
debug = true
overflow-checks = false

[profile.dev]
split-debuginfo = "unpacked"
overflow-checks = false
# wait until https://github.com/rust-lang/rust/issues/100142 fixed
incremental = false

[profile.dev.package]
addr2line = { opt-level = 3 }
adler = { opt-level = 3 }
gimli = { opt-level = 3 }
miniz_oxide = { opt-level = 3 }
object = { opt-level = 3 }
rustc-demangle = { opt-level = 3 }

[profile.test]
opt-level = 0
debug = 0
codegen-units = 16
lto = false
debug-assertions = true
overflow-checks = true
rpath = false

[patch.crates-io]
# If there are dependencies that need patching, they can be listed below.
# For example:
# arrow-format = { git = "https://github.com/datafuse-extras/arrow-format", rev = "78dacc1" }

arrow2 = { git = "https://github.com/jorgecarleitao/arrow2", rev = "db87f71" }
parquet2 = { git = "https://github.com/jorgecarleitao/parquet2", rev = "ed0e1ff" }
metrics = { git = "https://github.com/datafuse-extras/metrics.git", rev = "fc2ecd1" }
