[package]
name = "common-ast"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-exception = { path = "../../common/exception" }
common-functions = { path = "../functions" }
common-meta-app = { path = "../../meta/app" }
common-meta-types = { path = "../../meta/types" }

# Crates.io dependencies
fast-float = "0.2.0"
itertools = "0.10.5"
logos = "0.12.1"
nom = "7.1.1"
nom-rule = "0.3.0"
pratt = "0.3.0"
pretty = "0.11.3"
strum = "0.24"
strum_macros = "0.24"
url = "2.3.1"

[dev-dependencies]
common-base = { path = "../../common/base" }
criterion = "0.4"
goldenfile = "1.4"
pretty_assertions = "1.3.0"
regex = "1.6.0"

[[bench]]
name = "bench"
harness = false

[package.metadata.cargo-machete]
ignored = [
    "common-functions",
    "common-meta-types",
]
