[package]
name = "common-datavalues"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-arrow = { path = "../../common/arrow" }
common-exception = { path = "../../common/exception" }
common-hashtable = { path = "../../common/hashtable" }
common-io = { path = "../../common/io" }
primitive-types = "0.12.0"

# Github dependencies

# Crates.io dependencies
chrono = { version = "0.4.22", features = ["serde"] }
chrono-tz = "0.6.3"
dyn-clone = "1.0.9"
enum_dispatch = "0.3.8"
itertools = "0.10.5"
lexical-core = "0.8.5"
micromarshal = "0.2.0"
num = "0.4.0"
once_cell = "1.15.0"
ordered-float = "3.1.0"
paste = "1.0.9"
rand = { version = "0.8.5", features = ["small_rng"] }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
criterion = "0.4"
pretty_assertions = "1.3.0"
rand = "0.8.5"

[[bench]]
name = "builder"
harness = false

[[bench]]
name = "if_else_then"
harness = false

[[bench]]
name = "eq"
harness = false

[[bench]]
name = "data_type"
harness = false
