[package]
name = "common-management"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false
test = false

[dependencies]
common-base = { path = "../../common/base" }
common-exception = { path = "../../common/exception" }
common-functions = { path = "../functions" }
common-meta-api = { path = "../../meta/api" }
common-meta-kvapi = { path = "../../meta/kvapi" }
common-meta-store = { path = "../../meta/store" }
common-meta-types = { path = "../../meta/types" }
common-proto-conv = { path = "../../meta/proto-conv" }
common-protos = { path = "../../meta/protos" }

async-trait = "0.1.57"
serde_json = { workspace = true }

[dev-dependencies]
common-meta-embedded = { path = "../../meta/embedded" }
common-storage = { path = "../../common/storage" }
mockall = "0.11.2"
