[package]
name = "common-storages-parquet"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-arrow = { path = "../../../common/arrow" }
common-base = { path = "../../../common/base" }
common-catalog = { path = "../../catalog" }
common-config = { path = "../../config" }
common-exception = { path = "../../../common/exception" }
common-expression = { path = "../../expression" }
common-functions = { path = "../../functions" }
common-meta-app = { path = "../../../meta/app" }
common-pipeline-core = { path = "../../pipeline/core" }
common-storage = { path = "../../../common/storage" }

storages-common-pruner = { path = "../common/pruner" }
storages-common-table-meta = { path = "../common/table-meta" }

async-trait = { version = "0.1.57", package = "async-trait-fn" }
chrono = { workspace = true }
glob = "0.3.0"
opendal = { workspace = true }
serde = { workspace = true }
typetag = "0.2.3"

[dev-dependencies]
common-sql = { path = "../../sql" }
