[package]
name = "common-storages-parquet"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-arrow = { path = "../../../common/arrow" }
common-base = { path = "../../../common/base" }
common-catalog = { path = "../../../common/../query/catalog" }
common-config = { path = "../../../common/../query/config" }
common-datablocks = { path = "../../datablocks" }
common-datavalues = { path = "../../datavalues" }
common-exception = { path = "../../../common/exception" }
common-functions = { path = "../../functions" }
common-meta-app = { path = "../../../meta/app" }
common-pipeline-core = { path = "../../pipeline/core" }
common-sql = { path = "../../../common/../query/sql" }
common-storage = { path = "../../../common/storage" }

async-trait = { version = "0.1.57", package = "async-trait-fn" }
chrono = { workspace = true }
glob = "0.3.0"
opendal = "0.22"
serde = { workspace = true }
typetag = "0.2.3"
