[package]
name = "storages-common-pruner"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-exception = { path = "../../../../common/exception" }
common-expression = { path = "../../../expression" }
common-functions = { path = "../../../functions" }

storages-common-index = { path = "../index" }
storages-common-table-meta = { path = "../table-meta" }

serde = { workspace = true }
tracing = "0.1.36"
typetag = "0.2.3"
