[package]
name = "databend-query"
description = "A real-time Cloud Distributed Query Engine"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[features]
default = ["simd"]
simd = ["common-arrow/simd"]

tokio-console = ["common-tracing/console", "common-base/tracing"]
memory-profiling = ["common-base/memory-profiling", "common-http/memory-profiling", "tempfile"]
storage-hdfs = ["opendal/services-hdfs", "common-storage/storage-hdfs"]
hive = [
    "common-hive-meta-store",
    "thrift",
    "storage-hdfs",
    "common-config/hive",
    "common-storages-hive",
    "common-meta-app/storage-hdfs",
]
io-uring = [
    # "common-meta-embedded/io-uring",
    "common-meta-store/io-uring",
    # "common-meta-sled-store/io-uring",
    # "common-meta-raft-store/io-uring",
]

[dependencies]
# Workspace dependencies
common-arrow = { path = "../../common/arrow" }
common-ast = { path = "../ast" }
common-base = { path = "../../common/base" }
common-catalog = { path = "../catalog" }
common-config = { path = "../config" }
common-exception = { path = "../../common/exception" }
common-expression = { path = "../expression" }
common-formats = { path = "../formats" }
common-functions = { path = "../functions" }
common-grpc = { path = "../../common/grpc" }
common-hashtable = { path = "../../common/hashtable" }
common-hive-meta-store = { path = "../storages/hive/hive-meta-store", optional = true }
common-http = { path = "../../common/http" }
common-io = { path = "../../common/io" }
common-jsonb = { path = "../../common/jsonb" }
common-management = { path = "../management" }
common-meta-api = { path = "../../meta/api" }
common-meta-app = { path = "../../meta/app" }
# common-meta-embedded = { path = "../../meta/embedded" }
common-meta-store = { path = "../../meta/store" }
common-meta-types = { path = "../../meta/types" }
common-metrics = { path = "../../common/metrics" }
common-pipeline-core = { path = "../pipeline/core" }
common-pipeline-sinks = { path = "../pipeline/sinks" }
common-pipeline-sources = { path = "../pipeline/sources" }
common-pipeline-transforms = { path = "../pipeline/transforms" }
common-settings = { path = "../settings" }
common-sql = { path = "../sql" }
common-storage = { path = "../../common/storage" }
common-storages-factory = { path = "../storages/factory" }
common-storages-fuse = { path = "../storages/fuse" }
common-storages-hive = { path = "../storages/hive/hive", optional = true }
common-storages-information-schema = { path = "../storages/information-schema" }
common-storages-memory = { path = "../storages/memory" }
common-storages-null = { path = "../storages/null" }
common-storages-parquet = { path = "../storages/parquet" }
common-storages-random = { path = "../storages/random" }
common-storages-share = { path = "../storages/share" }
common-storages-stage = { path = "../storages/stage" }
common-storages-system = { path = "../storages/system" }
common-storages-view = { path = "../storages/view" }
common-tracing = { path = "../../common/tracing" }
common-users = { path = "../users" }
storages-common-cache = { path = "../storages/common/cache" }

storages-common-blocks = { path = "../storages/common/blocks" }
storages-common-cache-manager = { path = "../storages/common/cache-manager" }
storages-common-index = { path = "../storages/common/index" }
storages-common-table-meta = { path = "../storages/common/table-meta" }

# Github dependencies

# Crates.io dependencies
ahash = { version = "0.8.2", features = ["no-rng"] }
aho-corasick = { version = "0.7.20" }
async-channel = "1.7.1"
async-recursion = "1.0.0"
async-stream = "0.3.3"
async-trait = { version = "0.1.57", package = "async-trait-fn" }
backon = "0.4"
base64 = "0.13.0"
bincode = "1.3.3"
bstr = "1.0.1"
bumpalo = { workspace = true }
byteorder = "1.4.3"
bytes = "1.2.1"
chrono = { workspace = true }
chrono-tz = { workspace = true }
dashmap = "5.4"
futures = "0.3.24"
futures-util = "0.3.24"
headers = "0.3.8"
http = "0.2.8"
itertools = "0.10.5"
lz4 = "1.24.0"
match-template = "0.0.1"
metrics = "0.20.1"
naive-cityhash = "0.2.0"
once_cell = "1.15.0"
opendal = { workspace = true, features = ["layers-tracing", "layers-metrics", "compress"] }
opensrv-mysql = { git = "https://github.com/datafuselabs/opensrv", rev = "5e37788" }
parking_lot = "0.12.1"
petgraph = "0.6.2"
pin-project-lite = "0.2.9"
poem = { version = "1", features = ["rustls", "multipart", "compression"] }
primitive-types = "0.12.0"
rand = "0.8.5"
regex = "1.6.0"
semver = "1.0.14"
serde = { workspace = true }
serde_json = { workspace = true }
serde_urlencoded = "0.7.1"
state = "0.5"
tempfile = { version = "3.3.0", optional = true }
thrift = { package = "databend-thrift", version = "0.17.0", optional = true }
time = "0.3.14"
tokio-stream = { version = "0.1.10", features = ["net"] }
tonic = "0.8.1"
tracing = "0.1.36"
typetag = "0.2.3"
unicode-segmentation = "1.10.0"
uuid = { version = "1.1.2", features = ["serde", "v4"] }

[dev-dependencies]
common-meta-embedded = { path = "../../meta/embedded" }

base64 = "0.13.0"
criterion = "0.4"
goldenfile = "1.4"
hex = "0.4.3"
jwt-simple = "0.11.0"
maplit = "1.0.2"
mysql_async = { version = "0.31", default-features = false, features = ["rustls-tls"] }
num = "0.4.0"
p256 = "0.11"
pretty_assertions = "1.3.0"
reqwest = { workspace = true }
temp-env = "0.3.0"
tempfile = "3.3.0"
toml = { version = "0.5.9", default-features = false }
url = "2.3.1"
walkdir = "2.3.2"
wiremock = "0.5.14"

[build-dependencies]
common-building = { path = "../../common/building" }
