name: "Test meta data compatibility with openraft-07"
description: ""
inputs:
  profile:
    description: "The profile for this test"
    required: true
    default: "debug"
  target:
    description: ""
    required: true
    default: "x86_64-unknown-linux-gnu"
runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: ./.github/actions/artifact_download
      with:
        profile: ${{ inputs.profile }}
        sha: ${{ github.sha }}
        target: ${{ inputs.target }}

    - name: Test meta-data-compat-openraft-07
      shell: bash
      run: |
        bash ./tests/meta-data-compat-openraft-07/test-meta-data-compat-openraft-08.sh
