[package]
name = "databend-fuzz"
version = "0.1.0"
edition = "2021"
publish = false

# cargo can't build fuzz targets with afl
# split `fuzz` into separate workspace can help resolve this.
# add an empty `[workspace]` table to the package's manifest.
[workspace]

[[bin]]
name = "fuzz_parse_sql"
path = "fuzz_targets/fuzz_parse_sql.rs"
doctest = false
test = false

[dependencies]
common-ast = { path = ".." }

afl = "0.12"

[patch.crates-io]
parquet2 = { version = "0.14.1", optional = true, git = "https://github.com/datafuse-extras/parquet2", rev = "3a468fc3c4" }
