[package]
name = "storages-common-index"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[package.metadata.cargo-machete]
ignored = ["xorfilter-rs", "match-template"]

[dependencies]
common-arrow = { path = "../../../../common/arrow" }
common-exception = { path = "../../../../common/exception" }
common-expression = { path = "../../../expression" }
common-functions = { path = "../../../functions" }

storages-common-table-meta = { path = "../table-meta" }

anyerror = { workspace = true }
cbordata = { version = "0.6.0" }
match-template = "0.0.1"
serde = { workspace = true }
thiserror = { workspace = true }
tracing = "0.1.36"
xorfilter-rs = { git = "https://github.com/datafuse-extras/xorfilter", features = [
    "cbordata",
], tag = "databend-alpha.4" }

[dev-dependencies]
common-arrow = { path = "../../../../common/arrow" }
criterion = "0.4"
rand = "0.8.5"

[[bench]]
name = "build_from_block"
harness = false
