name: "Publish Binary"
description: "Publish releases binaries"
inputs:
  github_token:
    description: "GitHub token"
    required: true
  version:
    description: "Release version"
    required: true
  target:
    description: "Release target"
    required: true
  repo_role_arn:
    description: "Repo Role Arn"
    required: true
  mode:
    description: "Release Normal / Hive"
    required: false
    default: normal

runs:
  using: "composite"
  steps:
    - name: Get publish name
      id: name
      shell: bash
      run: |
        case ${{ inputs.mode }} in
          normal)
            publish_name="databend-${{ inputs.version }}-${{ inputs.target }}"
            ;;
          hive)
            publish_name="databend-hive-${{ inputs.version }}-${{ inputs.target }}"
            ;;
          *)
            echo "Unknown release mode: ${{ inputs.mode }}"
            exit 1
            ;;
        esac
        echo "name=$publish_name" >> $GITHUB_OUTPUT

    - name: Update release to github
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      # Reference: https://cli.github.com/manual/gh_release_upload
      run: |
        gh release upload ${{ inputs.version }} ${{ steps.name.outputs.name }}.*

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-duration-seconds: 900
        role-to-assume: ${{ inputs.repo_role_arn }}
        aws-region: us-east-2

    - name: Sync normal release to S3
      shell: bash
      if: inputs.mode == 'normal'
      run: |
        aws s3 cp ${{ steps.name.outputs.name }}.tar.gz s3://repo.databend.rs/databend/${{ inputs.version }}/${{ steps.name.outputs.name }}.tar.gz --no-progress
        curl --retry 3 -fsSLo tags.json \
            --header 'content-type: application/json' \
            --header 'authorization: Bearer ${{ inputs.github_token }}' \
            https://api.github.com/repos/datafuselabs/databend/tags
        cat tags.json
        aws s3 cp ./tags.json s3://repo.databend.rs/databend/tags.json
        curl --retry 3 -fsSLo releases.json \
            --header 'content-type: application/json' \
            --header 'authorization: Bearer ${{ inputs.github_token }}' \
            https://api.github.com/repos/datafuselabs/databend/releases
        cat releases.json
        aws s3 cp ./releases.json s3://repo.databend.rs/databend/releases.json
