[package]
name = "common-meta-api"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false
test = false

[dependencies]
common-exception = { path = "../../common/exception" }
common-expression = { path = "../../query/expression" }
common-meta-app = { path = "../app" }
common-meta-kvapi = { path = "../kvapi" }
common-meta-types = { path = "../types" }
common-proto-conv = { path = "../proto-conv" }
common-protos = { path = "../protos" }
common-tracing = { path = "../../common/tracing" }

anyhow = { workspace = true }
async-trait = "0.1.57"
chrono = { workspace = true }
enumflags2 = { version = "0.7.5", features = ["serde"] }
maplit = "1.0.2"
serde_json = { workspace = true }
tonic = { version = "0.8.1", features = ["transport", "codegen", "prost", "tls-roots", "tls"] }
tracing = "0.1.36"
