[package]
name = "common-storages-stage"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-base = { path = "../../../common/base" }
common-catalog = { path = "../../catalog" }
common-exception = { path = "../../../common/exception" }
common-expression = { path = "../../expression" }
common-formats = { path = "../../formats" }
common-meta-app = { path = "../../../meta/app" }
common-pipeline-core = { path = "../../pipeline/core" }
common-pipeline-sources = { path = "../../pipeline/sources" }
common-storage = { path = "../../../common/storage" }

async-trait = { version = "0.1.57", package = "async-trait-fn" }
opendal = { workspace = true }
parking_lot = "0.12.1"
uuid = { version = "1.1.2", features = ["serde", "v4"] }

[build-dependencies]
common-building = { path = "../../../common/building" }
