[package]
name = "common-sql"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-ast = { path = "../ast" }
common-base = { path = "../../common/base" }
common-catalog = { path = "../catalog" }
common-config = { path = "../config" }
common-exception = { path = "../../common/exception" }
common-expression = { path = "../expression" }
common-functions = { path = "../functions" }
common-meta-app = { path = "../../meta/app" }
common-meta-types = { path = "../../meta/types" }
common-profile = { path = "../../common/profile" }

common-pipeline-core = { path = "../pipeline/core" }
common-pipeline-sources = { path = "../pipeline/sources" }
common-pipeline-transforms = { path = "../pipeline/transforms" }

common-settings = { path = "../settings" }
common-storage = { path = "../../common/storage" }
common-storages-parquet = { path = "../storages/parquet" }
common-storages-result-cache = { path = "../storages/result_cache" }
common-storages-view = { path = "../storages/view" }
common-users = { path = "../users" }
storages-common-table-meta = { path = "../storages/common/table-meta" }

# Github dependencies

# Crates.io dependencies
ahash = { version = "0.8.2", features = ["no-rng"] }
anyhow = { workspace = true }
async-recursion = "1.0.0"
async-trait = { version = "0.1.57", package = "async-trait-fn" }
chrono = { workspace = true }
dashmap = "5.4"
globiter = "0.1"
itertools = "0.10.5"
once_cell = "1.15.0"
opendal = { workspace = true, features = ["layers-tracing", "layers-metrics"] }
ordered-float = { workspace = true }
parking_lot = "0.12.1"
percent-encoding = "2"
regex = "1.6.0"
roaring = "0.10.1"
serde = { workspace = true }
time = "0.3.14"
tracing = "0.1.36"
url = { version = "2.3" }
