name: "Build Linux"
description: "Build with profile"
inputs:
  target:
    description: ""
    required: true
  upload:
    description: "Upload artifact"
    required: false
    default: "true"
  artifacts:
    description: "Artifacts to build"
    required: false
    default: "sqllogictests,meta,query"
  features:
    description: "Features to build"
    required: false
    default: "default"
runs:
  using: "composite"
  steps:
    - name: Setup Build Tool
      uses: ./.github/actions/setup_build_tool
      with:
        target: ${{ inputs.target }}
        bypass_env_vars: RUSTFLAGS,RUST_LOG

    - name: Cross setup
      if: startsWith(inputs.target, 'aarch64-')
      shell: bash
      run: |
        echo "JEMALLOC_SYS_WITH_LG_PAGE=14" >> $GITHUB_ENV

    - name: Set Build Flags
      shell: bash
      run: |
        case ${{ inputs.target }} in
          x86_64-unknown-linux-gnu)
            flags="-C target-feature=+sse4.2"
            ;;
          x86_64-unknown-linux-musl)
            flags="-C target-feature=+sse4.2"
            ;;
          aarch64-unknown-linux-gnu)
            flags=""
            ;;
          aarch64-unknown-linux-musl)
            flags=""
            ;;
          *)
            flags=""
            ;;
        esac
        echo "RUSTFLAGS=${flags} -C link-arg=-Wl,--compress-debug-sections=zlib" >> $GITHUB_ENV
        target=${{ inputs.target }}
        echo "BUILD_ARCH=${target/-unknown-linux-*}" >> $GITHUB_ENV

    # build all binaries for debug
    - name: Build Debug
      if: env.BUILD_PROFILE == 'debug' && inputs.artifacts == 'all'
      shell: bash
      run: |
        cargo build --target ${{ inputs.target }} --features ${{ inputs.features }}
        ls -lh ./target/${{ inputs.target }}/${{ env.BUILD_PROFILE }}/databend-*

    - name: Build Debug for specific artifacts
      if: env.BUILD_PROFILE == 'debug' && inputs.artifacts != 'all'
      shell: bash
      run: |
        artifacts="${{ inputs.artifacts }}"
        for artifact in ${artifacts//,/ }; do
          echo "==> building databend-$artifact ..."
          cargo build --target ${{ inputs.target }} --features ${{ inputs.features }} --bin databend-$artifact
          ls -lh ./target/${{ inputs.target }}/${{ env.BUILD_PROFILE }}/databend-$artifact
        done

    - name: Build Release
      if: env.BUILD_PROFILE == 'release'
      shell: bash
      run: |
        artifacts="${{ inputs.artifacts }}"
        for artifact in ${artifacts//,/ }; do
          echo "==> building databend-$artifact ..."
          cargo build --target ${{ inputs.target }} --features ${{ inputs.features }} --release --bin databend-$artifact
          ls -lh ./target/${{ inputs.target }}/${{ env.BUILD_PROFILE }}/databend-$artifact
        done

    - shell: bash
      run: readelf -p .comment ./target/${{ inputs.target }}/${{ env.BUILD_PROFILE }}/databend-query

    # - name: Compress Binaries with UPX
    #   if: env.BUILD_PROFILE == 'debug'
    #   uses: crazy-max/ghaction-upx@v2
    #   with:
    #     files: ./target/${{ inputs.target }}/${{ env.BUILD_PROFILE }}/databend-*

    - name: Upload artifact
      if: inputs.upload == 'true'
      uses: ./.github/actions/artifact_upload
      with:
        sha: ${{ github.sha }}
        target: ${{ inputs.target }}
        category: ${{ inputs.features }}
