name: "Build Linux"
description: "Build with profile"
inputs:
  profile:
    description: "debug/release"
    required: true
  target:
    description: ""
    required: true
  upload:
    description: "Upload artifact"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Setup Build Tool
      uses: ./.github/actions/setup_build_tool
      with:
        image: ${{ inputs.target }}
        bypass_env_vars: RUSTFLAGS,RUST_LOG,je_cv_pthread_getname_np

    - name: Build Debug
      if: inputs.profile == 'debug'
      shell: bash
      run: cargo build --target ${{ inputs.target }}

    - name: Set Release build flags
      if: inputs.profile == 'release'
      shell: bash
      run: |
        case ${{ inputs.target }} in
          x86_64-unknown-linux-gnu)
            flags="-C target-feature=+sse4.2"
            ;;
          x86_64-unknown-linux-musl)
            flags="-C target-feature=+sse4.2 -C link-arg=-Wl,--compress-debug-sections=zlib-gabi"
            ;;
          aarch64-unknown-linux-gnu)
            flags=""
            ;;
          aarch64-unknown-linux-musl)
            flags="-C link-arg=-Wl,--compress-debug-sections=zlib-gabi"
            ;;
          *)
            flags=""
            ;;
        esac
        echo "RUSTFLAGS=${flags}" >> $GITHUB_ENV
        target=${{ inputs.target }}
        echo "BUILD_ARCH=${target/-unknown-linux-*}" >> $GITHUB_ENV

    - name: Build Release
      if: inputs.profile == 'release'
      shell: bash
      run: cargo build --target ${{ inputs.target }} --release

    - shell: bash
      run: readelf -p .comment ./target/${{ inputs.target }}/${{ inputs.profile }}/databend-query

    - name: Copyobj zlib for gnu binaries
      if: inputs.profile == 'release' && endsWith(inputs.target, '-gnu')
      shell: bash
      run: |
        build-tool /usr/bin/${{ env.BUILD_ARCH }}-linux-gnu-objcopy --compress-debug-sections=zlib-gnu ./target/${{ inputs.target }}/release/databend-query
        build-tool /usr/bin/${{ env.BUILD_ARCH }}-linux-gnu-objcopy --compress-debug-sections=zlib-gnu ./target/${{ inputs.target }}/release/databend-meta
        build-tool /usr/bin/${{ env.BUILD_ARCH }}-linux-gnu-objcopy --compress-debug-sections=zlib-gnu ./target/${{ inputs.target }}/release/databend-metactl

    - name: Upload artifact
      if: inputs.upload == 'true'
      uses: ./.github/actions/artifact_upload
      with:
        profile: ${{ inputs.profile }}
        sha: ${{ github.sha }}
        target: ${{ inputs.target }}
