[package]
name = "common-expression"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
test = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-arrow = { path = "../../common/arrow" }
common-datavalues = { path = "../datavalues" }
common-exception = { path = "../../common/exception" }
common-io = { path = "../../common/io" }

# Github dependencies

# Crates.io dependencies
chrono = { workspace = true }
chrono-tz = { workspace = true }
comfy-table = "6"
common-jsonb = { path = "../../common/jsonb" }
educe = "0.4"
enum-as-inner = "0.5"
enum_dispatch = "0.3.8"
futures = "0.3.24"
hex = "0.4.3"
itertools = "0.10"
lexical-core = "0.8.5"
match-template = "0.0.1"
micromarshal = "0.2.1"
num-traits = "0.2.15"
ordered-float = { workspace = true, features = ["serde", "rand"] }
parking_lot = "0.12.1"
primitive-types = "0.12.0"
rand = { version = "0.8.5", features = ["small_rng"] }
rust_decimal = "1.26"
serde = { workspace = true }
serde_json = { workspace = true }
tracing = "0.1.36"
typetag = "0.2.3"

[dev-dependencies]
common-ast = { path = "../ast" }
goldenfile = "1.4"
pretty_assertions = "1.3.0"
rand = "0.8.5"
