[package]
name = "common-expression"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
test = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-arrow = { path = "../../common/arrow" }
common-datablocks = { path = "../datablocks" }
common-datavalues = { path = "../datavalues" }
common-exception = { path = "../../common/exception" }
common-io = { path = "../../common/io" }

# Github dependencies

# Crates.io dependencies
chrono = "0.4"
chrono-tz = "0.6.3"
comfy-table = "6"
common-jsonb = { path = "../../common/jsonb" }
educe = "0.4"
enum-as-inner = "0.5"
hex = "0.4.3"
itertools = "0.10"
lexical-core = "0.8.5"
match-template = "0.0.1"
num-traits = "0.2.15"
ordered-float = { version = "3.1.0", features = ["serde"] }
rust_decimal = "1.26"
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
common-ast = { path = "../ast" }
goldenfile = "1.4"
rand = "0.8.5"
