# Usage:
# databend-query -c databend_query_config_spec.toml

[query]
max_active_sessions = 256
wait_timeout_mills = 5000

# For flight rpc.
flight_api_address = "0.0.0.0:9090"

# Databend Query http address.
# For admin RESET API.
admin_api_address = "0.0.0.0:8080"

# Databend Query metrics RESET API.
metric_api_address = "0.0.0.0:7070"

# Databend Query MySQL Handler.
mysql_handler_host = "0.0.0.0"
mysql_handler_port = 3307

# Databend Query ClickHouse HTTP Handler.
clickhouse_http_handler_host = "0.0.0.0"
clickhouse_http_handler_port = 8124

# Databend Query HTTP Handler.
http_handler_host = "0.0.0.0"
http_handler_port = 8000

tenant_id = "default"
cluster_id = "default"

[log]

[log.file]
level = "INFO"
format = "text"
dir = "./.databend/logs"


[meta]
endpoints = ["0.0.0.0:9191"]
username = "root"
password = "root"
client_timeout_in_second = 60

# Storage config.
[storage]
# fs|s3
type = "fs"

# fs storage.
[storage.fs]
data_path = "./.databend/data"
