[package]
name = "common-meta-store"
description = "MetaStore is impl with either a local embedded meta store, or a grpc-client of metasrv"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[features]
io-uring = ["common-meta-embedded/io-uring"]

[dependencies]
# Workspace dependencies
common-grpc = { path = "../../common/grpc" }
common-meta-client = { path = "../client" }
common-meta-embedded = { path = "../embedded" }
common-meta-kvapi = { path = "../kvapi" }
common-meta-types = { path = "../types" }

# Crates.io dependencies
async-trait = "0.1.57"
tracing = "0.1.36"
