[package]
name = "common-hive-meta-store"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[features]
# Phony feature 
#
# Prevents the integration tests from running if "hive" not enabled 
#   The integration tests need hive-meta-store service, which is not available 
#   in the normal testing setup.
hive-it = []

[dependencies] # In alphabetical order
# Workspace dependencies

# Github dependencies
thrift = { git = "https://github.com/datafuse-extras/thrift", tag = "v0.17.0" }

# Crates.io dependencies

[build-dependencies]
which = "4.3.0"
