[package]
name = "common-metrics"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies
common-exception = { path = "../exception" }

# Crates.io dependencies
metrics = "0.20.1"
metrics-exporter-prometheus = { version = "0.11.0", default-features = false }
once_cell = "1.15.0"
parking_lot = "0.12.1"
prometheus-parse = "0.2.3"
serde = { workspace = true }
tracing = "0.1.36"

[target.'cfg(target_os = "linux")'.dependencies]
procfs = "0.12.0"

[dev-dependencies]
anyhow = { workspace = true }

[dev-dependencies.tokio]
default-features = false
features = ["io-util", "net", "sync", "rt-multi-thread", "macros"]
version = "1.24.2"
