name: "Test Fuzz Standalone"
description: "Running fuzz tests in standalone mode"
inputs:
  profile:
    description: "The profile for this test"
    required: true
    default: "debug"
  target:
    description: ""
    required: true
    default: "x86_64-unknown-linux-gnu"
runs:
  using: "composite"
  steps:
    - name: Setup Build Tool
      uses: ./.github/actions/setup_build_tool

    - name: Download artifact
      uses: ./.github/actions/artifact_download
      with:
        profile: ${{ inputs.profile }}
        sha: ${{ github.sha }}
        target: ${{ inputs.target }}

    - name: Run fuzz Tests with Standalone mode with embedded meta-store
      shell: bash
      run: |
        build-tool bash ./scripts/ci/ci-run-fuzz-tests.sh

    - name: Upload failure
      if: failure() || cancelled()
      uses: ./.github/actions/artifact_failure
      with:
        name: test-fuzz-standalone-linux
