name: "Test Stateless Standalone"
description: "Running stateless tests in standalone mode"
inputs:
  target:
    description: ""
    required: true
    default: "x86_64-apple-darwin"
runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: ./.github/actions/artifact_download
      with:
        sha: ${{ github.sha }}
        target: ${{ inputs.target }}

    - name: Test setup
      shell: bash
      run: |
        bash ./scripts/setup/dev_setup.sh -yd

    - name: Run Stateless Tests with Standalone mode
      shell: bash
      run: |
        bash ./scripts/ci/ci-run-stateless-tests-standalone.sh

    - name: Upload failure
      if: failure() || cancelled()
      uses: ./.github/actions/artifact_failure
      with:
        name: test-stateless-standalone-macos
