[package]
name = "common-meta-raft-store"
description = "Raft state machine"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[features]
io-uring = ["common-meta-sled-store/io-uring"]

[dependencies]
common-exception = { path = "../../common/exception" }
common-grpc = { path = "../../common/grpc" }
common-meta-api = { path = "../api" }
common-meta-kvapi = { path = "../kvapi" }
common-meta-sled-store = { path = "../sled-store" }
common-meta-stoerr = { path = "../stoerr" }
common-meta-types = { path = "../types" }
common-tracing = { path = "../../common/tracing" }

openraft = { workspace = true }

# crates.io deps
anyhow = { workspace = true }
async-trait = "0.1.57"
byteorder = "1.4.3"
chrono = { workspace = true }
derive_more = { workspace = true }
hostname = "0.3.1"
maplit = "1.0.2"
num = "0.4.0"
once_cell = "1.15.0"
serde = { workspace = true }
serde_json = { workspace = true }
tracing = "0.1.36"

[dev-dependencies]
common-base = { path = "../../common/base" }

async-entry = "0.3.1"
pretty_assertions = "1.3.0"
tempfile = "3.3.0"
