[package]
name = "databend-meta-upgrade-09"
description = "upgrade meta-service data to VER=24"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[dependencies]
# Workspace dependencies
common-meta-api = { path = "../../meta/api" }
common-meta-app = { path = "../../meta/app" }
common-meta-raft-store = { path = "../../meta/raft-store" }
common-meta-sled-store = { path = "../../meta/sled-store" }
common-meta-types = { path = "../../meta/types" }
common-proto-conv = { path = "../../meta/proto-conv" }
common-protos = { path = "../../meta/protos" }
common-tracing = { path = "../../common/tracing" }

# Crates.io dependencies
anyhow = { workspace = true }
clap = { workspace = true }
openraft = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { version = "1.21.1", features = ["full"] }
tracing = "0.1.36"

[[bin]]
name = "databend-meta-upgrade-09"
path = "src/main.rs"
doctest = false
test = false
