[package]
name = "common-protos"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
num-derive = "0.3.3"
num-traits = "0.2.15"
prost = { workspace = true }
tonic = { version = "0.8.1", features = ["transport", "codegen", "prost", "tls-roots", "tls"] }

[build-dependencies]
prost-build = "0.11.1"
semver = "1"
tonic-build = "0.8.0"

[dev-dependencies]

[package.metadata.cargo-machete]
ignored = ["num-derive", "num-traits"]
