[package]
name = "common-protos"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
num-derive = "0.3.3"
num-traits = "0.2.15"
prost = { workspace = true }
tonic = { workspace = true }

[build-dependencies]
lenient_semver = "0.4.2"
prost-build = "0.11.1"
semver = "1"
tonic-build = { workspace = true }

[dev-dependencies]

[package.metadata.cargo-machete]
ignored = ["num-derive", "num-traits"]
