[package]
name = "common-functions-v2"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-arrow = { path = "../../common/arrow" }
common-exception = { path = "../../common/exception" }
common-expression = { path = "../expression" }
common-hashtable = { path = "../../common/hashtable" }
common-io = { path = "../../common/io" }
common-jsonb = { path = "../../common/jsonb" }

# Crates.io dependencies
base64 = "0.13.0"
bstr = "1.0.1"
bumpalo = "3.11.0"
bytes = "1.2.1"
chrono = { workspace = true }
chrono-tz = { workspace = true }
crc32fast = "1.3.2"
criterion = "0.4"
hex = "0.4.3"
itertools = "0.10.5"
match-template = "0.0.1"
memchr = "2.5.0"
num-traits = "0.2.15"
once_cell = "1.15.0"
ordered-float = { version = "3.1.0", features = [
    "serde",
    "rand",
] }
rand = { version = "0.8.5", features = ["small_rng"] }
regex = "1.6.0"
serde = { workspace = true }
simdutf8 = "0.1.4"
siphasher = "0.3"
streaming_algorithms = { git = "https://github.com/datafuse-extras/streaming_algorithms", tag = "hyperloglog_del_op_fix_overflow_bug" }
strength_reduce = "0.2.3"

[dev-dependencies]
comfy-table = "6"
common-ast = { path = "../ast" }
goldenfile = "1.4"

[[bench]]
name = "bench"
harness = false
