[package]
name = "common-storages-share"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
chrono = { workspace = true }
common-exception = { path = "../../../common/exception" }
common-meta-app = { path = "../../../meta/app" }
enumflags2 = { version = "0.7.7", features = ["serde"] }

storages-common-table-meta = { path = "../common/table-meta" }

async-backtrace = { workspace = true }
opendal = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
goldenfile = "1.4"
tempfile = "3.4.0"
