[package]
name = "common-storages-share"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-exception = { path = "../../../common/exception" }
common-meta-app = { path = "../../../meta/app" }
common-storages-table-meta = { path = "../table-meta" }

opendal = "0.23"
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
goldenfile = "1.4"
tempfile = "3.3.0"
