[package]
name = "common-meta-types"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
common-meta-stoerr = { path = "../stoerr" }

openraft = { workspace = true }

anyerror = { workspace = true }
derive_more = { workspace = true }
num-derive = "0.3.3"
num-traits = "0.2.15"
once_cell = "1.15.0"
prost = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true }

[build-dependencies]
common-building = { path = "../../common/building" }
prost-build = "0.11.1"
tonic-build = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
regex = "1.8.1"

[package.metadata.cargo-machete]
ignored = ["num-derive", "prost"]
