[package]
name = "common-meta-types"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
common-exception = { path = "../../common/exception" }
common-meta-stoerr = { path = "../stoerr" }
common-storage = { path = "../../common/storage" }

openraft = { workspace = true }

anyerror = { workspace = true }
chrono = { workspace = true }
derive_more = "0.99.17"
enumflags2 = { version = "0.7.5", features = ["serde"] }
hex = "0.4.3"
num-derive = "0.3.3"
num-traits = "0.2.15"
once_cell = "1.15.0"
prost = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha1 = "0.10.5"
sha2 = "0.10.6"
thiserror = { workspace = true }
tonic = { version = "0.8.1", features = ["transport", "codegen", "prost", "tls-roots", "tls"] }

[build-dependencies]
common-building = { path = "../../common/building" }
prost-build = "0.11.1"
tonic-build = "0.8.0"

[dev-dependencies]
anyhow = { workspace = true }
regex = "1.6.0"
