[package]
name = "common-io"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies
common-exception = { path = "../exception" }

# Crates.io dependencies
bincode = { version = "2.0.0-rc.1", features = ["serde", "std"] }
bytes = "1.2.1"
chrono = { workspace = true }
chrono-tz = { workspace = true }
ethnum = "1.3.2"
lexical-core = "0.8.5"
micromarshal = "0.3.0"
ordered-float = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
aho-corasick = { version = "0.7.20" }
rand = "0.8.5"
