[package]
name = "common-functions"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies] # In alphabetical order
# Workspace dependencies
common-arrow = { path = "../../common/arrow" }
common-base = { path = "../../common/base" }
common-datablocks = { path = "../datablocks" }
common-datavalues = { path = "../datavalues" }
common-exception = { path = "../../common/exception" }
common-hashtable = { path = "../../common/hashtable" }
common-io = { path = "../../common/io" }
common-jsonb = { path = "../../common/jsonb" }

# Crates.io dependencies
base64 = "0.13.0"
blake3 = "1.3.1"
bstr = "1.0.1"
bumpalo = "3.11.0"
bytes = "1.2.1"
chrono = { workspace = true }
chrono-tz = { workspace = true }
crc32fast = "1.3.2"
dyn-clone = "1.0.9"
geo-types = "0.7.7"
h3ron = "0.15.1"
hex = "0.4.3"
itertools = "0.10.5"
md-5 = "0.10.5"
naive-cityhash = "0.2.0"
num = "0.4.0"
num-format = "0.4.0"
num-traits = "0.2.15"
once_cell = "1.15.0"
ordered-float = { version = "3.1.0", features = ["serde"] }
pulldown-cmark = { version = "0.9.2", default-features = false }
rand = { version = "0.8.5", features = ["small_rng"] }
regex = "1.6.0"
rust-embed = { version = "6.4.1", features = ["debug-embed"] }
serde = { workspace = true }
serde_json = { workspace = true }
sha1 = "0.10.5"
sha2 = "0.10.6"
simdutf8 = "0.1.4"
siphasher = "0.3"
streaming_algorithms = { git = "https://github.com/datafuse-extras/streaming_algorithms", tag = "hyperloglog_del_op_fix_overflow_bug" }
strength_reduce = "0.2.3"
twox-hash = "1.6.3"
uuid = { version = "1.1.2", features = ["v4"] }

[dev-dependencies]
bumpalo = "3.11.0"
float-cmp = "0.9.0"
pretty_assertions = "1.3.0"
