[package]
name = "databend-binaries"
description = "databend command line tools"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[features]
default = ["simd", "jemalloc", "z3-prove"]
memory-profiling = ["databend-meta/memory-profiling", "databend-query/memory-profiling", "common-base/memory-profiling"]
simd = ["databend-meta/simd", "databend-query/simd"]
z3-prove = ["databend-query/z3-prove"]
jemalloc = ["common-base/jemalloc"]
tokio-console = [
    "databend-meta/tokio-console",
    "databend-query/io-uring",
    "common-base/tracing",
    "common-tracing/console",
]
io-uring = [
    "databend-meta/io-uring",
    "databend-query/io-uring",
    "common-meta-store/io-uring",
    "common-meta-sled-store/io-uring",
    "common-meta-raft-store/io-uring",
]

enable-histogram-metrics = [
    "default",
    "common-metrics/enable-histogram",
    "databend-query/enable-histogram-metrics",
]

[dependencies]
# Workspace dependencies
common-base = { path = "../common/base" }
common-config = { path = "../query/config" }
common-exception = { path = "../common/exception" }
common-expression = { path = "../query/expression" }
common-grpc = { path = "../common/grpc" }
common-license = { path = "../common/license" }
common-meta-api = { path = "../meta/api" }
common-meta-app = { path = "../meta/app" }
common-meta-client = { path = "../meta/client" }
common-meta-kvapi = { path = "../meta/kvapi" }
common-meta-raft-store = { path = "../meta/raft-store" }
common-meta-sled-store = { path = "../meta/sled-store" }
common-meta-stoerr = { path = "../meta/stoerr" }
common-meta-store = { path = "../meta/store" }
common-meta-types = { path = "../meta/types" }
common-metrics = { path = "../common/metrics" }
common-storage = { path = "../common/storage" }
common-tracing = { path = "../common/tracing" }
databend-meta = { path = "../meta/service" }
databend-query = { path = "../query/service" }
enterprise-query = { path = "../query/ee" }
# enterprise-meta = { path = "../meta/ee" }
sharing-endpoint = { path = "../query/sharing-endpoint" }
storages-common-table-meta = { path = "../query/storages/common/table-meta" }

# Crates.io dependencies
anyerror = { workspace = true }
anyhow = { workspace = true }
async-backtrace = { workspace = true }
clap = { workspace = true }
comfy-table = "6.1.3"
limits-rs = "0.2.0"
opendal = { workspace = true }
poem = { version = "1", features = ["rustls", "multipart", "compression"] }
sentry = { version = "0.30", default-features = false, features = [
    "backtrace",
    "contexts",
    "panic",
    "reqwest",
    "rustls",
] }
serde = { workspace = true }
serde_json = { workspace = true }
serfig = "0.1.0"
tokio = { workspace = true }
tokio-stream = "0.1.10"
tonic = { workspace = true }
tracing = "0.1.36"
url = "2.3.1"

[[bin]]
name = "databend-meta"
path = "meta/ee_main.rs"
doctest = false
test = false

[[bin]]
name = "databend-meta-oss"
path = "meta/oss_main.rs"
doctest = false
test = false

[[bin]]
name = "databend-metabench"
path = "metabench/main.rs"
doctest = false
test = false

[[bin]]
name = "databend-metactl"
path = "metactl/main.rs"
doctest = false
test = false

[[bin]]
name = "databend-query"
path = "query/ee_main.rs"
doctest = false
test = false

[[bin]]
name = "databend-query-oss"
path = "query/oss_main.rs"
doctest = false
test = false

[[bin]]
name = "open-sharing"
path = "opensharing/main.rs"
doctest = false
test = false

[[bin]]
name = "table-meta-inspector"
path = "tool/table_meta_inspector.rs"
doctest = false
test = false
