[package]
name = "storages-common-table-meta"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[features]

[dependencies]
common-arrow = { path = "../../../../common/arrow" }
common-base = { path = "../../../../common/base" }
common-cache = { path = "../../../../common/cache" }
common-config = { path = "../../../config" }
common-datavalues = { path = "../../../datavalues" }
common-exception = { path = "../../../../common/exception" }
common-expression = { path = "../../../expression" }

async-trait = { version = "0.1.57", package = "async-trait-fn" }
chrono = { workspace = true }
enum-as-inner = "0.5"
metrics = "0.20.1"
once_cell = "1.15.0"
opendal = { workspace = true }
parking_lot = "0.12.1"
serde = { workspace = true }
