[package]
name = "storages-common-table-meta"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[features]

[dependencies]
common-arrow = { path = "../../../../common/arrow" }
common-base = { path = "../../../../common/base" }
common-datavalues = { path = "../../../datavalues" }
common-exception = { path = "../../../../common/exception" }
common-expression = { path = "../../../expression" }

chrono = { workspace = true }
enum-as-inner = "0.5"
once_cell = "1.15.0"
serde = { workspace = true }
