name: "Test Stateful Large Data"
description: "Running stateful with large data"
inputs:
  profile:
    description: "The profile for this test"
    required: true
    default: "debug"
  target:
    description: ""
    required: true
    default: "x86_64-unknown-linux-gnu"
runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: ./.github/actions/artifact_download
      with:
        profile: ${{ inputs.profile }}
        sha: ${{ github.sha }}
        target: ${{ inputs.target }}

    - name: Run Stateful Tests with Standalone mode
      shell: bash
      env:
        TEST_ID: github-${{ github.run_id }}
      run: |
        ./scripts/ci/ci-run-stateful-tests-large-data-s3.sh

    - name: Upload failure
      if: failure() || cancelled()
      uses: ./.github/actions/artifact_failure
      with:
        name: test-stateful-large-data
