name: "Upload Artifacts"
description: "Upload build Result Binaries"
inputs:
  sha:
    description: "git sha"
    required: true
  target:
    description: ""
    required: true
  category:
    description: "default/hive"
    required: false
    default: default
outputs:
  src:
    description: ""
    value: ${{ steps.info.outputs.src }}
runs:
  using: "composite"
  steps:
    - name: Get Upload Info
      id: info
      shell: bash
      run: |
        if [[ "${RUNNER_PROVIDER}" == "aws" ]]; then
          src="s3"
        else
          src="github"
        fi
        echo "src=${src}" >> $GITHUB_OUTPUT

    - name: Upload artifact to github
      if: steps.info.outputs.src == 'github'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.BUILD_PROFILE }}-${{ inputs.sha }}-${{ inputs.target }}-${{ inputs.category }}
        path: ./target/${{ inputs.target }}/${{ env.BUILD_PROFILE }}/databend-*

    - name: Upload open-sharing to github
      if: steps.info.outputs.src == 'github'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.BUILD_PROFILE }}-${{ inputs.sha }}-${{ inputs.target }}-${{ inputs.category }}
        path: ./target/${{ inputs.target }}/${{ env.BUILD_PROFILE }}/open-sharing

    - name: Upload artifacts to s3
      if: steps.info.outputs.src == 's3'
      shell: bash
      run: |
        aws s3 sync ./target/${{ inputs.target }}/${{ env.BUILD_PROFILE }}/ \
          s3://databend-ci/${{ env.BUILD_PROFILE }}/${{ inputs.sha }}/${{ inputs.target }}/${{ inputs.category }}/ \
          --exclude "*" --include "databend-*" --no-progress
        aws s3 cp ./target/${{ inputs.target }}/${{ env.BUILD_PROFILE }}/open-sharing s3://databend-ci/${{ env.BUILD_PROFILE }}/${{ inputs.sha }}/${{ inputs.target }}/${{ inputs.category }}/ --no-progress || true
