[package]
name = "enterprise-query"
description = "A real-time Cloud Distributed Query Engine"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies]
# Workspace dependencies
async-backtrace = { workspace = true }
common-base = { path = "../../common/base" }
common-catalog = { path = "../catalog" }
common-config = { path = "../config" }
common-exception = { path = "../../common/exception" }
common-license = { path = "../../common/license" }
common-settings = { path = "../../query/settings" }
common-storages-fuse = { path = "../storages/fuse" }
databend-query = { path = "../service" }
storages-common-cache = { path = "../storages/common/cache" }
storages-common-table-meta = { path = "../storages/common/table-meta" }
vacuum-handler = { path = "../ee-features/vacuum-handler" }

async-trait = "0.1.57"
chrono = { workspace = true }
dashmap = "5.4"
jwt-simple = "0.11.0"
tracing = "0.1.36"

[build-dependencies]
common-building = { path = "../../common/building" }

[package.metadata.cargo-machete]
ignored = ["match-template"]
