name: "Setup BendSQL"
description: "Setup BendSQL for CI"
inputs:
  version:
    description: "bendsql version"
    required: false
    default: v0.3.7
runs:
  using: "composite"
  steps:
    - name: Download and Install
      shell: bash
      run: |
        curl -fsSLo ./bendsql.tar.gz https://github.com/datafuselabs/bendsql/releases/download/${{ inputs.version }}/bendsql-x86_64-unknown-linux-gnu.tar.gz
        tar -xvzf ./bendsql.tar.gz
        chmod +x ./bendsql
        sudo cp ./bendsql /usr/local/bin/bendsql
        rm -rf ./bendsql
        rm -rf ./bendsql.tar.gz
        bendsql --version
