[package]
name = "common-base"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[features]
tracing = ["tokio/tracing"]
memory-profiling = [
    "tikv-jemalloc-ctl",
    "tikv-jemalloc-sys/stats",
    "tikv-jemalloc-sys/profiling",
    "tikv-jemalloc-sys/unprefixed_malloc_on_supported_platforms",
]

[dependencies] # In alphabetical order
# Workspace dependencies
common-exception = { path = "../exception" }

# Github dependencies

# Crates.io dependencies
async-channel = "1.7.1"
async-trait = "0.1.57"
ctrlc = { version = "3.2.3", features = ["termination"] }
futures = "0.3.24"
libc = "0.2.133"
num_cpus = "1.13.1"
once_cell = "1.15.0"
pprof = { version = "0.10.1", features = [
    "flamegraph",
    "protobuf-codec",
    "protobuf",
] }
semver = "1.0.10"
serde = { workspace = true }
tikv-jemalloc-ctl = { version = "0.4.2", optional = true }
tikv-jemalloc-sys = "0.4.3"
tokio = { version = "1.21.1", features = ["full"] }
tracing = "0.1.36"
uuid = { version = "1.1.2", features = ["serde", "v4"] }

[dev-dependencies]
anyhow = { workspace = true }
rand = "0.8.3"
