name: "Download Artifacts"
description: "Download build Result Binaries"
inputs:
  profile:
    description: "debug/release"
    required: true
  sha:
    description: "git sha"
    required: true
  target:
    description: ""
    required: true
  category:
    description: "default/hive"
    required: false
    default: default
  path:
    description: "default to ./target/{inputs.profile}/"
    required: false
    default: ""
outputs:
  path:
    description: ""
    value: ${{ steps.info.outputs.path }}
  src:
    description: ""
    value: ${{ steps.info.outputs.src }}
runs:
  using: "composite"
  steps:
    - name: Get Download Info
      id: info
      shell: bash
      run: |
        if [[ -z "${{ inputs.path }}" ]]; then
          path="./target/${{ inputs.profile }}"
        else
          path="${{ inputs.path }}"
        fi
        echo "path=${path}" >> $GITHUB_OUTPUT

        if [[ "${RUNNER_PROVIDER}" == "aws" ]]; then
          src="s3"
        else
          src="github"
        fi
        echo "src=${src}" >> $GITHUB_OUTPUT

    - uses: actions/download-artifact@v3
      if: steps.info.outputs.src == 'github'
      with:
        name: ${{ inputs.profile }}-${{ inputs.sha }}-${{ inputs.target }}-${{ inputs.category }}
        path: ${{ steps.info.outputs.path }}/

    - name: Download artifact from s3
      if: steps.info.outputs.src == 's3'
      shell: bash
      run: |
        aws s3 sync \
          s3://databend-ci/${{ inputs.profile }}/${{ inputs.sha }}/${{ inputs.target }}/${{ inputs.category }}/ \
          ${{ steps.info.outputs.path }}/ --exclude "*" --include "databend-*" --no-progress
        aws s3 sync \
          s3://databend-ci/${{ inputs.profile }}/${{ inputs.sha }}/${{ inputs.target }}/${{ inputs.category }}/ \
          ${{ steps.info.outputs.path }}/ --exclude "*" --include "open-sharing" --no-progress || true

    - name: make artifacts executable
      shell: bash
      run: |
        chmod +x ${{ steps.info.outputs.path }}/databend-*
        chmod +x ${{ steps.info.outputs.path }}/open-sharing || true
