[package]
name = "common-formats"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
bstr = "1.0.1"
chrono-tz = { workspace = true }
lexical-core = "0.8.5"
match-template = "0.0.1"
micromarshal = "0.4.0"
num = "0.4.0"
ordered-float = { workspace = true }
roaring = { version = "0.10.1", features = ["serde"] }
serde_json = { workspace = true }

# Workspace dependencies
common-arrow = { path = "../../common/arrow" }
common-exception = { path = "../../common/exception" }
common-expression = { path = "../expression" }
common-io = { path = "../../common/io" }
common-meta-app = { path = "../../meta/app" }
common-settings = { path = "../settings" }
jsonb = { workspace = true }

storages-common-blocks = { path = "../storages/common/blocks" }
storages-common-table-meta = { path = "../storages/common/table-meta" }

[dev-dependencies]
common-arrow = { path = "../../common/arrow" }

pretty_assertions = "1.3.0"

[package.metadata.cargo-machete]
ignored = ["match-template"]
