[package]
name = "common-formats"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false
test = false

[dependencies] # In alphabetical order
bstr = "1.0.1"
chrono = { workspace = true }
chrono-tz = { workspace = true }
lexical-core = "0.8.5"
micromarshal = "0.2.1"
num = "0.4.0"
ordered-float = { workspace = true }
serde_json = { workspace = true }

# Workspace dependencies
common-arrow = { path = "../../common/arrow" }
common-exception = { path = "../../common/exception" }
common-expression = { path = "../expression" }
common-io = { path = "../../common/io" }
common-jsonb = { path = "../../common/jsonb" }
common-meta-types = { path = "../../meta/types" }
common-settings = { path = "../settings" }

storages-common-blocks = { path = "../storages/common/blocks" }
storages-common-table-meta = { path = "../storages/common/table-meta" }

# Crates.io dependencies
once_cell = "1.15.0"

[dev-dependencies]
common-arrow = { path = "../../common/arrow" }

pretty_assertions = "1.3.0"
