[package]
name = "common-storages-table-meta"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[features]

[dependencies]
common-arrow = { path = "../../../common/arrow" }
common-base = { path = "../../../common/base" }
common-cache = { path = "../../../common/cache" }
common-config = { path = "../../config" }
common-datablocks = { path = "../../datablocks" }
common-datavalues = { path = "../../datavalues" }
common-exception = { path = "../../../common/exception" }
common-metrics = { path = "../../../common/metrics" }

chrono = { workspace = true }
metrics = "0.20.1"
once_cell = "1.15.0"
parking_lot = "0.12.1"
serde = { workspace = true }
