name: "Create Check Status"
description: "Create check status on github commit"
inputs:
  github_token:
    description: "GitHub Token"
    required: true
  sha:
    description: "commit sha"
    required: true
  state:
    description: "check state, can be one of: error, failure, pending, success"
    required: true
  context:
    description: "check title"
    required: true
  description:
    description: "check description"
    required: false

runs:
  using: "composite"
  steps:
    # Docs: https://docs.github.com/en/rest/checks/runs#create-a-check-run
    # Rest: https://octokit.github.io/rest.js/v18#checks-create

    # https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#create-a-commit-status
    - name: Create a check Status
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/statuses/${{ inputs.sha }} \
          -f state='${{ inputs.state }}' \
         -f target_url='https://github.com/datafuselabs/databend/actions/runs/${{ github.run_id }}' \
         -f description='${{ inputs.description }}' \
         -f context='${{ inputs.context }}'
