name: "Test old metasrv is compatible with new query"
description: "Download old binaries and current binaries, run stateless test with old `meta` and latest `query`"
inputs:
  profile:
    description: ""
    required: true
    default: "debug"
  target:
    description: ""
    required: true
    default: "x86_64-unknown-linux-gnu"
runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: ./.github/actions/artifact_download
      with:
        profile: ${{ inputs.profile }}
        sha: ${{ github.sha }}
        target: ${{ inputs.target }}
        path: ./bins/current

    - name: Test compatibility
      shell: bash
      run: |
        bash ./tests/compat/test-compat.sh

    - name: Upload failure
      if: failure() || cancelled()
      uses: ./.github/actions/artifact_failure
      with:
        name: test-compat
