[package]
name = "common-sharing"
version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies]
anyhow = { workspace = true }
async-trait = "0.1"
backon = "0.4"
base64 = "0.13.0"
bytes = "1"
common-auth = { path = "../../common/auth" }
common-config = { path = "../config" }

http = "0.2"
log = "0.4"
moka = "0.10"
opendal = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { version = "1" }
