name: "Check Run EE"
description: "Check Whether pull requests should run Enterprise tests"
inputs:
  target:
    description: ""
    required: true
    default: "x86_64-unknown-linux-gnu"
outputs:
  skip-ee-check:
    description: "If it is true, skip enterprise integration tests"
    value: ${{ steps.checker.outputs.skip-ee-check }}
runs:
  using: "composite"
  steps:
    - name: Check if PR is from a forked repository
      shell: bash
      id: checker
      run: |
        if [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]; then
          echo "This PR is from a forked repository"
          echo "PR Repo: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "Base Repo: ${{ github.repository }}"
          echo "skip enterprise license tests"
          echo "skip-ee-check=true" >> $GITHUB_OUTPUT
        else
          echo "This PR is from the base repository"
          echo "start enterprise license tests"
          echo "skip-ee-check=false" >> $GITHUB_OUTPUT
        fi
