# Usage:
# databend-query -c databend_query_config_spec.toml

[query]
max_active_sessions = 256
wait_timeout_mills = 5000

# For flight rpc.
flight_api_address = "0.0.0.0:9093"

# Databend Query http address.
# For admin RESET API.
admin_api_address = "0.0.0.0:8083"

# Databend Query metrics RESET API.
metric_api_address = "0.0.0.0:7073"

# Databend Query MySQL Handler.
mysql_handler_host = "0.0.0.0"
mysql_handler_port = 3309


# Databend Query ClickHouse Handler.
clickhouse_http_handler_host = "0.0.0.0"
clickhouse_http_handler_port = 8127

# Databend Query HTTP Handler.
http_handler_host = "0.0.0.0"
http_handler_port = 8003

# Databend Query FlightSQL Handler.
flight_sql_handler_host = "0.0.0.0"
flight_sql_handler_port = 8903

tenant_id = "test_tenant"
cluster_id = "test_cluster"

table_engine_memory_enabled = true
default_storage_format = 'parquet'
default_compression = 'zstd'

[log]

[log.file]
level = "INFO"
format = "text"
dir = "./.databend/logs_3"

[meta]
# It is a list of `grpc_api_advertise_host:<grpc-api-port>` of databend-meta config
endpoints = ["0.0.0.0:9191"]
username = "root"
password = "root"
client_timeout_in_second = 60
auto_sync_interval = 60

# Storage config.
[storage]
# fs | s3 | azblob | obs | oss
type = "s3"

# Set a local folder to store your data.
# Comment out this block if you're NOT using local file system as storage.
[storage.fs]
data_path = "./.databend/stateless_test_data"

[storage.s3]
bucket = "databend"
endpoint_url = "http://172.17.0.4:9000"
access_key_id = "minioadmin"
secret_access_key = "minioadmin"
enable_virtual_host_style = false

# Cache config.
[cache]
# Type of storage to keep the table data cache
#
# available options: [none|disk]
# default is "none", which disable table data cache
# use "disk" to enabled disk cache
data_cache_storage = "none"

[cache.disk]
# cache path
path = "./.databend/_cache"
# max bytes of cached data 20G
max_bytes = 21474836480

