name: Benchmark

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "website/**"
      - "**.md"
      - "docker/**"
      - ".devcontainer/**"
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to run benchmark
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

env:
  BUILD_PROFILE: release
  RUNNER_PROVIDER: aws
  CARGO_INCREMENTAL: 0
  # Remove this env after rust 1.68 has been released.
  CARGO_UNSTABLE_SPARSE_REGISTRY: true

jobs:
  build_release:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'ci-benchmark')
    timeout-minutes: 30
    runs-on: [self-hosted, X64, Linux, perf]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}
          fetch-depth: 0
      - uses: ./.github/actions/build_linux
        with:
          target: x86_64-unknown-linux-gnu
          profile: release

  clickbench:
    needs: build_release
    timeout-minutes: 30
    runs-on: [self-hosted, X64, Linux, perf]
    strategy:
      matrix:
        storage:
          - s3
          - fs
        dataset:
          - hits
          - tpch
    steps:
      - uses: actions/checkout@v3
      - name: Get benchmark source
        run: |
          case ${{ github.event_name }} in
            pull_request)
              echo "BENCHMARK_SOURCE=pr" > $GITHUB_ENV
              echo "BENCHMARK_SOURCE_ID=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
              ;;
            workflow_dispatch)
              echo "BENCHMARK_SOURCE=release" > $GITHUB_ENV
              echo "BENCHMARK_SOURCE_ID=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
              ;;
            *)
              echo "Unknown event name: ${{ github.event_name }}"
              exit 1
              ;;
          esac
      - uses: ./.github/actions/benchmark
        with:
          storage: ${{ matrix.storage }}
          dataset: ${{ matrix.dataset }}
          source: ${{ env.BENCHMARK_SOURCE }}
          source_id: ${{ env.BENCHMARK_SOURCE_ID }}
