name: Benchmark

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "website/**"
      - "**.md"
      - "docker/**"
      - ".devcontainer/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

env:
  BUILD_PROFILE: release
  RUNNER_PROVIDER: aws

jobs:
  build_release:
    if: contains(github.event.pull_request.labels.*.name, 'ci-benchmark')
    timeout-minutes: 30
    runs-on: [self-hosted, X64, Linux, perf]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}
          fetch-depth: 0
      - uses: ./.github/actions/build_linux
        with:
          target: x86_64-unknown-linux-gnu
          profile: release
      - name: Generate benchmark metadata
        run: |
          echo '{}' > metadata.json
          jq ".sha = \"${{ github.sha }}\"" <metadata.json >metadata.json.tmp && mv metadata.json.tmp metadata.json
          jq ".run_id = \"${{ github.run_id }}\"" <metadata.json >metadata.json.tmp && mv metadata.json.tmp metadata.json
          jq ".pr_id = \"${{ github.event.pull_request.number }}\"" <metadata.json >metadata.json.tmp && mv metadata.json.tmp metadata.json
          jq ".head_sha = \"${{ github.event.pull_request.head.sha }}\"" <metadata.json >metadata.json.tmp && mv metadata.json.tmp metadata.json
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-metadata
          path: metadata.json
