name: Dev Linux

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      # - labeled
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "website/**"
      - "**.md"
      - "docker/**"
      - "scripts/setup/**"
      - ".devcontainer/**"
  merge_group:
    types:
      - checks_requested

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

env:
  BUILD_PROFILE: debug
  RUNNER_PROVIDER: aws

jobs:
  check:
    runs-on: [self-hosted, X64, Linux, 8c16g]
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all tags, metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/check
        timeout-minutes: 30
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    timeout-minutes: 30
    name: build_${{ matrix.arch }}_${{ matrix.libc }}
    runs-on: [self-hosted, X64, Linux, 16c32g]
    strategy:
      matrix:
        include:
          - { arch: x86_64, libc: gnu }
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all tags, metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/build_linux
        with:
          target: ${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}
          profile: debug

  build_other:
    timeout-minutes: 30
    name: build_${{ matrix.arch }}_${{ matrix.libc }}
    runs-on: [self-hosted, X64, Linux, 8c16g]
    strategy:
      matrix:
        include:
          - { arch: x86_64, libc: musl }
          - { arch: aarch64, libc: musl }
          - { arch: aarch64, libc: gnu }
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all tags, metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/build_linux
        with:
          target: ${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}
          profile: debug

  build_hive:
    timeout-minutes: 30
    runs-on: [self-hosted, X64, Linux, 8c16g]
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all tags, metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/build_linux_hive
        with:
          target: x86_64-unknown-linux-gnu
          profile: debug

  test_unit:
    runs-on: [self-hosted, X64, Linux, 8c16g]
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all tags, metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/test_unit
        timeout-minutes: 30

  test_metactl:
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_metactl
        timeout-minutes: 10

  test_meta-upgrade-09:
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_meta-upgrade-09
        timeout-minutes: 10

  test_meta-data-compat-openraft-07:
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_meta_data_compat_openraft_07
        timeout-minutes: 10

  test_compat:
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_compat
        timeout-minutes: 10

  test_compat_fuse:
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/fuse_compat
        timeout-minutes: 10

  test_meta_cluster:
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_meta_cluster
        timeout-minutes: 10

  test_sqllogic_standalone:
    name: test_sqllogic_standalone_${{ matrix.dirs }}
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    strategy:
      matrix:
        dirs:
          - "query"
          - "standalone"
          - "crdb"
          - "duckdb"
        handlers:
          - "mysql,http,clickhouse"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_sqllogic_standalone_linux
        timeout-minutes: 30
        with:
          dirs: ${{ matrix.dirs }}
          handlers: ${{ matrix.handlers }}
          storage-format: all
      - name: Upload failure
        if: failure() || cancelled()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-sqllogic-standalone-${{ matrix.handlers }}-${{ matrix.dirs }}

  test_sqllogic_standalone_with_native:
    name: test_sqllogic_standalone_${{ matrix.dirs }}_${{ matrix.format }}
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    strategy:
      matrix:
        dirs:
          - "base"
          - "ydb"
        format:
          - "parquet"
          - "native"
        handlers:
          - "mysql,http,clickhouse"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_sqllogic_standalone_linux
        timeout-minutes: 30
        with:
          dirs: ${{ matrix.dirs }}
          handlers: ${{ matrix.handlers }}
          storage-format: ${{ matrix.format }}
      - name: Upload failure
        if: failure() || cancelled()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-sqllogic-standalone-${{ matrix.handlers }}-${{ matrix.dirs }}_${{ matrix.format }}


  test_sqllogic_management_mode:
    timeout-minutes: 30
    name: test_sqllogic_${{ matrix.dirs }}
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    strategy:
      matrix:
        dirs:
          - "management"
        handlers:
          - "mysql,http,clickhouse"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_sqllogic_management_mode_linux
        with:
          dirs: ${{ matrix.dirs }}
          handlers: ${{ matrix.handlers }}

  test_sqllogic_cluster:
    name: test_sqllogic_cluster_${{ matrix.dirs }}
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    strategy:
      matrix:
        dirs:
          - "base"
          - "query"
          - "cluster"
          - "ydb"
          - "crdb"
          - "duckdb"
        handlers:
          - "mysql,http,clickhouse"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_sqllogic_cluster_linux
        timeout-minutes: 30
        with:
          dirs: ${{ matrix.dirs }}
          handlers: ${{ matrix.handlers }}
      - name: Upload failure
        if: failure() || cancelled()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-sqllogic-cluster-${{ matrix.handlers }}-${{ matrix.dirs }}

  test_stateless_standalone:
    timeout-minutes: 20
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateless_standalone_linux

  test_stateless_cluster:
    timeout-minutes: 30
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateless_cluster_linux

  test_stateful_standalone:
    timeout-minutes: 20
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateful_standalone_linux

  test_stateful_cluster:
    timeout-minutes: 20
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateful_cluster_linux

  test_stateful_large_data:
    timeout-minutes: 60
    if: contains(github.event.pull_request.labels.*.name, 'ci-largedata')
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateful_large_data

  test_fuzz_standalone:
    timeout-minutes: 10
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_fuzz_standalone_linux
        continue-on-error: true

  test_stateful_hive_standalone:
    timeout-minutes: 10
    runs-on: [self-hosted, X64, Linux, 4c8g]
    needs: build_hive
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateful_hive_standalone
        with:
          target: x86_64-unknown-linux-gnu
          profile: debug
