name: Dev Linux

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "website/**"
      - "**.md"
      - "docker/**"
      - "scripts/setup/**"
      - ".devcontainer/**"
  merge_group:
    types:
      - checks_requested

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

env:
  BUILD_PROFILE: debug
  RUNNER_PROVIDER: aws

jobs:
  check:
    runs-on: [self-hosted, X64, Linux, dev]
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all tags,  metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/check
        timeout-minutes: 30
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build_gnu:
    timeout-minutes: 30
    name: build_${{ matrix.arch }}_gnu
    runs-on: [self-hosted, X64, Linux, dev]
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all tags,  metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/build_linux
        with:
          target: ${{ matrix.arch }}-unknown-linux-gnu
          profile: debug

  build_musl:
    timeout-minutes: 30
    name: build_${{ matrix.arch }}_musl
    runs-on: [self-hosted, X64, Linux, dev]
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all tags,  metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/build_linux
        env:
          # To avoid the `undefined reference to pthread_getname_np` error during linking,
          # here we override set config environment var `je_cv_pthread_getname_np` to `no`,
          # as suggested by tikv-jemalloc-sys's maintainer @BusyJay:
          # https://github.com/tikv/jemallocator/issues/30#issuecomment-1183786410
          #
          # Hopefully this trick can be removed when rust upgraded to musl 1.2.3
          # https://github.com/rust-lang/rust/pull/102891
          je_cv_pthread_getname_np: no
        with:
          target: ${{ matrix.arch }}-unknown-linux-musl
          profile: debug

  test_unit:
    runs-on: [self-hosted, X64, Linux, dev]
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all tags,  metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/test_unit
        timeout-minutes: 30
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}

  test_metactl:
    runs-on: [self-hosted, X64, Linux, dev]
    needs: build_gnu
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_metactl
        timeout-minutes: 10

  test_meta-upgrade-09:
    runs-on: [self-hosted, X64, Linux, dev]
    needs: build_gnu
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_meta-upgrade-09
        timeout-minutes: 10

  test_meta-data-compat-openraft-07:
    runs-on: [self-hosted, X64, Linux, dev]
    needs: build_gnu
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_meta_data_compat_openraft_07
        timeout-minutes: 10

  test_compat:
    runs-on: [self-hosted, X64, Linux, dev]
    needs: build_gnu
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_compat
        timeout-minutes: 10

  fuse_compat:
    runs-on: [self-hosted, X64, Linux, dev]
    needs: build_gnu
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/fuse_compat
        timeout-minutes: 10

  test_meta_cluster:
    runs-on: [self-hosted, X64, Linux, dev]
    needs: build_gnu
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_meta_cluster
        timeout-minutes: 10

  test_sqllogic_standalone_linux:
    name: test_sqllogic_${{ matrix.dirs }}_standalone_linux
    runs-on: [self-hosted, X64, Linux, dev]
    needs: build_gnu
    strategy:
      matrix:
        dirs:
          - "base"
          - "query"
          - "standalone"
          - "ydb"
          - "crdb"
          - "duckdb"
        handlers:
          - "mysql,http,clickhouse"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_sqllogic_standalone_linux
        timeout-minutes: 30
        with:
          dirs: ${{ matrix.dirs }}
          handlers: ${{ matrix.handlers }}
      - name: Upload failure
        if: failure() || cancelled()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-sqllogic-standalone-${{ matrix.handlers }}-${{ matrix.dirs }}

  test_sqllogic_management_mode_linux:
    timeout-minutes: 30
    name: test_sqllogic_${{ matrix.dirs }}_linux
    runs-on: [self-hosted, X64, Linux, dev]
    needs: build_gnu
    strategy:
      matrix:
        dirs:
          - "management"
        handlers:
          - "mysql,http,clickhouse"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_sqllogic_management_mode_linux
        with:
          dirs: ${{ matrix.dirs }}
          handlers: ${{ matrix.handlers }}

  test_sqllogic_cluster_linux:
    name: test_sqllogic_${{ matrix.dirs }}_cluster_linux
    runs-on: [self-hosted, X64, Linux, dev]
    needs: build_gnu
    strategy:
      matrix:
        dirs:
          - "base"
          - "query"
          - "cluster"
          - "ydb"
          - "crdb"
          - "duckdb"
        handlers:
          - "mysql,http,clickhouse"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_sqllogic_cluster_linux
        timeout-minutes: 30
        with:
          dirs: ${{ matrix.dirs }}
          handlers: ${{ matrix.handlers }}
      - name: Upload failure
        if: failure() || cancelled()
        uses: ./.github/actions/artifact_failure
        with:
          name: test-sqllogic-cluster-${{ matrix.handlers }}-${{ matrix.dirs }}

  test_stateless_standalone_linux:
    timeout-minutes: 20
    runs-on: [self-hosted, X64, Linux, dev]
    needs: build_gnu
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateless_standalone_linux

  test_stateless_cluster_linux:
    timeout-minutes: 30
    runs-on: [self-hosted, X64, Linux, dev]
    needs: build_gnu
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateless_cluster_linux

  test_stateful_standalone_linux:
    timeout-minutes: 20
    runs-on: [self-hosted, X64, Linux, dev]
    needs: build_gnu
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateful_standalone_linux

  test_stateful_cluster_linux:
    timeout-minutes: 20
    runs-on: [self-hosted, X64, Linux, dev]
    needs: build_gnu
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateful_cluster_linux

  test_stateful_large_data:
    timeout-minutes: 60
    if: contains(github.event.pull_request.labels.*.name, 'ci-largedata')
    runs-on: [self-hosted, X64, Linux, dev]
    needs: build_gnu
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateful_large_data

  test_fuzz_standalone_linux:
    timeout-minutes: 10
    runs-on: [self-hosted, X64, Linux, dev]
    needs: build_gnu
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_fuzz_standalone_linux
        continue-on-error: true

  build_hive:
    timeout-minutes: 30
    runs-on: [self-hosted, X64, Linux, dev]
    steps:
      - uses: actions/checkout@v3
        with:
          # fetch all tags,  metasrv and metaclient need tag as its version.
          fetch-depth: 0
      - uses: ./.github/actions/build_linux_hive
        with:
          target: x86_64-unknown-linux-gnu
          profile: debug

  test_stateful_hive_standalone:
    timeout-minutes: 10
    runs-on: [self-hosted, X64, Linux, dev]
    needs: build_hive
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test_stateful_hive_standalone
        with:
          target: x86_64-unknown-linux-gnu
          profile: debug
